services:
  api:
    image: ${IMAGE}
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./prod-data:/app/api/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/app/api/data/prod.db
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION:-af-south-1}
